### ISSUE TITLE
Does it work?

### ISSUE THREAD

**Issue by olivetree123** [MichaelAquilina/python-tools#18]
when I find variables in python code , it always shows 'python-tools could not find any results' 
mac 10.11.1

**Comment by edwinksl** [comment]
Yeah this feature is quite buggy: it works for some variables and not others.

**Comment by MichaelAquilina** [comment]
Unfortunately this all depends on what Jedi returns to me. Could you paste me an example code snippet that doesn't work for you and what function you are trying to use (i.e. show usages or goto definition).
