### ISSUE TITLE
Selecting multiline strings

### ISSUE THREAD

**Issue by kbrose** [MichaelAquilina/python-tools#20]
Selecting a multi-line string that is created using parentheses and implicit string concatenation only selects a portion of the string.

Example multi-line string:

``` python
s = ('this is a string '
'that spans multiple '
'lines.')
# equivalent to s = 'this is a string that spans multiple lines.'
```

but when using `ctrl+alt+e` to select the string, it only selects a portion, i.e. only `'this is a string '`. Perhaps this behavior is what is desired, but I want to make sure it's intentional and not accidental.

Windows 8.1

**Comment by MichaelAquilina** [comment]
This is actually a case I didn't think of. I'll try work on this on the weekend. Thanks for posting this issue.
