### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by krishna444** [MichaelAquilina/python-tools#33]
I could not install this package in my Windows 10 system. I am a Python programmer and using Atom IDE to develop projects. But problem is I could not install this package properly. After installation, I get the error message which says:

**exit with code 1, signal null**

But I have no idea how this error popped up. BTW, it works in Linux systems without any problems. 

Is this a bug in windows 10?

**Comment by MichaelAquilina** [comment]
Hi @krishna444 I am not all too sure since I have not used a Windows machine in a long time. Can you look at the existing Issues and see if any of them look like the problem you have experienced?

**Comment by MichaelAquilina** [comment]
This should be fixed in the latest python-tools release
