### ISSUE TITLE
I have installed python but python-tools was unable to find....

### ISSUE THREAD

**Issue by Danceiny** [MichaelAquilina/python-tools#34]
In my machine, which is windows7 64bit,  I have reinstalled a pluggin named **Wakatime**, (because the plugin didn't work normally).but I don't know why when I launch Atom, the error always shows up:
```
python-tools was unable to find your machine's python executable.

Please try set the path in package settings and then restart atom.

If the issue persists please post an issue on https://github.com/michaelaquilina/python-tools/issues/new
Error: spawn python ENOENT
```

I have checked the following points listed in <https://atom.io/packages/python-tools>, and made sure of that nothing goes wrong:
* Make sure python is installed on your machine (jedi is used internally which runs off python)
* Make sure your python executable is added to your PATH environment variable

**So what should I do?**
Excuse of my little English. 
Best Regards.

**Comment by ItamarShDev** [comment]
[FIX](https://github.com/MichaelAquilina/python-tools/issues/38#issuecomment-216195217)
thanks to [@zhangkaizhao](https://github.com/zhangkaizhao)
