### ISSUE TITLE
python-tools was unable to find your machine's python executable.

### ISSUE THREAD

**Issue by meiyougithub** [MichaelAquilina/python-tools#35]
Suddenly the python in atom does not work. The error is:

Please try set the path in package settings and then restart atom.
Error: spawn python ENOENT

I didn't change the path in the environment settings. The path in system variables:

![image](https://cloud.githubusercontent.com/assets/17996871/14591819/ab89a788-04e5-11e6-84ec-e51c44a84489.png)

Thanks

**Comment by Laranto** [comment]
Got the same error. 
Was running before, no change to the path was made.

**Comment by zhangkaizhao** [comment]
My solution: https://github.com/MichaelAquilina/python-tools/issues/38#issuecomment-216195217

**Comment by MichaelAquilina** [comment]
Fixed in python-tools 0.6.8 thanks to @go2sh for the fix
