### ISSUE TITLE
python-tools was unable to find my machine's python executable ? what should I do?

### ISSUE THREAD

**Issue by Vincentqyw** [MichaelAquilina/python-tools#36]

**Comment by crocodilus** [comment]
Same issue here.  Apparently triggered by this morning's update to atom.

`Error: spawn python ENOENT`

**Comment by sunnybesunny** [comment]
Experiencing the same issue. It was working just fine yesterday

**Comment by just-calm** [comment]
Me too. Ant the python path setting's  in config also do't work .It's fine yesterday

**Comment by madrus** [comment]
Same here.

**Comment by ItamarShDev** [comment]
same as #34

**Comment by MichaelAquilina** [comment]
Fixed in python-tools 0.6.8 thanks to @go2sh for the fix

**Comment by challakarthik9** [comment]
same here

**Comment by Faan111** [comment]
same here

**Comment by Abhaypareek170** [comment]
Same here

**Comment by YoonAvril** [comment]
1. python-tools set path to python directory: /usr/local/Cellar/python/3.7.3/bin
2. export PATH= /usr/local/Cellar/python/3.7.3/bin:$PATH (.bashrc)
3. restart atom
not find local venv's packages
