### ISSUE TITLE
python-tools overwrites process-wide PATH variable

### ISSUE THREAD

**Issue by toadicus** [MichaelAquilina/python-tools#37]
Around python-tools.coffee line 73, python-tools writes to process.env.PATH using the paths found and guessed for the python executable.  This prevents other plugins from spawning child processes using the system's environmental PATH variable.  I recommend that python-tools avoid assigning anything to process.env.PATH to promote compatibility with other plugins.

See also kriscross07/atom-gpp-compiler#14

**Comment by go2sh** [comment]
See #48  :-)

**Comment by MichaelAquilina** [comment]
Fixed in python-tools 0.6.8 thanks to @go2sh for the fix
