### ISSUE TITLE
"python-tools was unable to find your machine's python executable" on Windows

### ISSUE THREAD

**Issue by lgcc** [MichaelAquilina/python-tools#38]
in addition to python-tools, linter-pep8 and linter-flake8 seems not to find their executable path either. However, I am pretty sure I have set python path in Windows %PATH%, I can find it use python
in both Powershell and Command Prompt. I am using Miniconda2 32-bit python, and I can find Python registry information under " \HKLM\SOFTWARE\Wow6432Node\Python ". Why Atom can not find it

**Comment by FurryFur** [comment]
I have the same bug, I'm using Anaconda 4 64bit with Python 3.5.1. I tried manually adding the python path in settings also but I still get the same error.

**Comment by gocarlos** [comment]
I sencod this

**Comment by Talvalin** [comment]
I had Python 3.4 and Python 2.7 installed on my machine, then installed Atom and Python Tools. Things were absolutely fine until I upgraded my Python 2.7 to a later version, and then I started hitting this issue. :(

**Comment by zhangkaizhao** [comment]
Using this dir path string:

`C:\Users\zhangkaizhao\AppData\Local\Programs\Python\Python35`

instead of:

`C:\\Users\\zhangkaizhao\\AppData\\Local\\Programs\\Python\\Python35`

resolve this problem for me. Hope this helps you.

**Comment by theCompanyDream** [comment]
@zhangkaizhao is that the path environment variable or is that some where in the configuration

**Comment by zhangkaizhao** [comment]
@theCompanyDream in the configuration

**Comment by go2sh** [comment]
I found the bug. I will submit a pull request. The `process.env` object is now case sensitiv.

**Comment by MichaelAquilina** [comment]
Fixed in python-tools 0.6.8 thanks to @go2sh for the fix

**Comment by davidyapdy** [comment]
For windows

1. search for "run" in windows
2. type "regedit" 
3. look into HKEY_CURRENT_USER
4. select "Enviroment"
5. select PATH
6. add the path at the end of the line separated by ; .

example: 
C:\Users\xxxxxx\AppData\Roaming\npm;C:\Users\xxxxxxx\AppData\Local\atom\bin;C:\Users\xxxxxx\AppData\Local\Programs\Python\Python35-32
