### ISSUE TITLE
Python tools is not fiding my exe paths, yet they are added by default at installation (of both 2.7 and 3.5.1)

### ISSUE THREAD

**Issue by KalsCode** [MichaelAquilina/python-tools#43]
![python tools error](https://cloud.githubusercontent.com/assets/12933332/15522829/ec160a98-21c9-11e6-931d-cd06cc031c88.PNG)

**Comment by scottpidzarko** [comment]
I have it only installed for my user with 3.5.1 and the executable is by default at C:\Users\<username>\AppData\Local\Programs\Python\Python35.  I would suggest adding this to the list of places the package looks.

**Comment by KalsCode** [comment]
Yes I added it to the path  (I put 3.5.1 and 2.7 as the first and second
parameter of the path) and works well now. Thanks alot.

**Comment by MichaelAquilina** [comment]
Fixed in python-tools 0.6.8 thanks to @go2sh for the fix
