### ISSUE TITLE
Error while installing python tools on atom, windows platform

### ISSUE THREAD

**Issue by zemuldo** [MichaelAquilina/python-tools#62]
python-tools was unable to find your machine's python executable.

Please try set the path in package settings and then restart atom.

If the issue persists please post an issue on https://github.com/michaelaquilina/python-tools/issues/new
Error: spawn python ENOENT

**Comment by MichaelAquilina** [comment]
I believe this was fixed with the latest version of python tools. Could you tell me what version you are currently using?

**Comment by 9994444ggg** [comment]
Hello I answer you to late but my Python installation is Private.
Thank you your Question by and i hope you find another connection for yoour Python.
