### ISSUE TITLE
import netCDF4 does not work while other imports work

### ISSUE THREAD

**Issue by ArashMehraban** [MichaelAquilina/python-tools#70]
I am on a Ubuntu 14.04 machine. I installed anaconda2. Then installed netCDF4 using the conda package manger. So when I use python on a terminal and say 
from netCDF4 import Dataset
It does work. Now, in the python-tools package, I gave the path to where anaconda2 reaches python 2.7:
$HOME/anaconda2/bin/python2.7
but when I run the python code that says 
from netCDF4 import Dataset,

I get this error:
Traceback (most recent call last):
  File "/home/arash/converter/reader.py", line 3, in <module>
    from netCDF4 import Dataset
ImportError: No module named netCDF4

**Comment by MCilento93** [comment]
It worked for me to set (within python-tools package settings the path of my current environment
(reboot atom next)

![image](https://user-images.githubusercontent.com/66259011/101279979-92bf6080-37c6-11eb-870a-1165fafa6bed.png)

**Comment by MCilento93** [comment]
(all the packages in conda are in the root written below)
![image](https://user-images.githubusercontent.com/66259011/101280037-f9dd1500-37c6-11eb-8017-584f6f395840.png)

**Comment by ArashMehraban** [comment]
Thanks! I am no longer using Ubuntu 14 or Atom.
