### ISSUE TITLE
Detailed changelog

### ISSUE THREAD

**Issue by Grumphette** [MichaelAquilina/python-tools#9]
Dear author,

I have seen two update from your pythin-tools i use but the changelog still is empty, so i have no idea of what is changed. 

Regards

**Comment by MichaelAquilina** [comment]
Hi @Grumphette 
You are completely right of course, It's basically laziness from my side. I'll make a bigger effort to update the changelog from now on.

Major changes are usually reflected in the README. For example I recently added a tool for conveniently selecting strings.

**Comment by Grumphette** [comment]
This brings me to my other question, why using the "go to definition" and
not the already existing "go to declaration" (or it is the other way
around, but you got the point ;) )

Grumphette

**Comment by MichaelAquilina** [comment]
Well "Go to Declaration" does not with with python symbols. I chose to stick to "Go to Definition" because that's referred to in the python API and I didnt want to shadow existing commands in Atom.

**Comment by MichaelAquilina** [comment]
@Grumphette check the CHANGELOG for the latest release. I have started making it a point to list changes as you requested. I'll be closing this Issue as a result. Feel free to re-open it if you feel it does not suffice.

**Comment by Grumphette** [comment]
I just saw the changelog, lately i could not re open Atom, That is great :)

Grumphette
